### ISSUE TITLE
Create more gracious exit on missing paths

### ISSUE THREAD

**Issue by Obiwantje** [uwedeportivo/romba#118]
Currently when for instance the depot folder is missing (but defined in the .ini) - rombaserver will hard crash GO on startup. Please implement folder check based on .ini and provide gracious exit with message.

**Comment by Obiwantje** [comment]
Example of the error below. - The path  /home/thejay/romba.tst/_ditweg is defined in .ini but not available.

I0406 12:07:40.863730   14136 kv.go:148] Loading SHA1 DB
I0406 12:07:40.893108   14136 kv.go:155] Loading CRC -> SHA1 DB
I0406 12:07:40.919115   14136 kv.go:162] Loading MD5 -> SHA1 DB
I0406 12:07:40.946304   14136 db.go:110] Done Loading DB in 0s
I0406 12:07:40.946338   14136 depot.go:64] Depot init
I0406 12:07:40.946350   14136 depot.go:75] establishing size of /home/thejay/romba.tst/_ditweg
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7d218b]

goroutine 1 [running]:
github.com/uwedeportivo/romba/archive.(*sizeVisitor).visit(0xc42001b580, 0xc4200149c0, 0x1e, 0x0, 0x0, 0xd8bf20, 0xc420123d40, 0xc420123d40, 0xc420133d40)
	/home/thejay/go/src/github.com/uwedeportivo/romba/archive/sizes.go:140 +0x3b
github.com/uwedeportivo/romba/archive.(*sizeVisitor).(github.com/uwedeportivo/romba/archive.visit)-fm(0xc4200149c0, 0x1e, 0x0, 0x0, 0xd8bf20, 0xc420123d40, 0x10, 0x8a7e40)
	/home/thejay/go/src/github.com/uwedeportivo/romba/archive/sizes.go:152 +0x69
path/filepath.Walk(0xc4200149c0, 0x1e, 0xc42011fb78, 0xd8bf20, 0xc420123d10)
	/usr/local/go/src/path/filepath/path.go:401 +0x76
github.com/uwedeportivo/romba/archive.calcSize(0xc4200149c0, 0x1e, 0x0, 0xd8bf20, 0xc420123d10)
	/home/thejay/go/src/github.com/uwedeportivo/romba/archive/sizes.go:152 +0x87
github.com/uwedeportivo/romba/archive.establishSize(0xc4200149c0, 0x1e, 0xc42011fcb0, 0x1, 0x1)
	/home/thejay/go/src/github.com/uwedeportivo/romba/archive/sizes.go:164 +0x81
github.com/uwedeportivo/romba/archive.NewDepot(0xc420136d30, 0x1, 0x1, 0xc42001b428, 0x1, 0x1, 0xd95920, 0xc42010e900, 0xc42011fd68, 0xc42011feb8, ...)
	/home/thejay/go/src/github.com/uwedeportivo/romba/archive/depot.go:76 +0x38a
main.main()
	/home/thejay/go/src/github.com/uwedeportivo/romba/cmds/rombaserver/main.go:176 +0xaa8
thejay@sv-ASUS-Z87A:~/romba.tst$
